# Generated by Django 4.1.1 on 2023-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actors', to='movies_app.actor', verbose_name='Актори'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='film_director', to='movies_app.actor', verbose_name='Режисер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies_app.genre', verbose_name='Жанри'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва фільму'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва фільму'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва фільму'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва фільму'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Рік'),
        ),
    ]
