# Generated by Django 4.1.1 on 2023-04-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_alter_movie_actors_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='description_uk',
            new_name='description_pl',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='name_uk',
            new_name='name_pl',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description_uk',
            new_name='description_pl',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_uk',
            new_name='name_pl',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='description_uk',
            new_name='description_pl',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name_uk',
            new_name='name_pl',
        ),
        migrations.RenameField(
            model_name='movieshot',
            old_name='description_uk',
            new_name='description_pl',
        ),
        migrations.RenameField(
            model_name='movieshot',
            old_name='title_uk',
            new_name='title_pl',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country_uk',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline_uk',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_uk',
        ),
        migrations.AddField(
            model_name='movie',
            name='country_pl',
            field=models.CharField(max_length=30, null=True, verbose_name='Analog in English'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_pl',
            field=models.TextField(null=True, verbose_name='Analog in English'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline_pl',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Film title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actors', to='movies_app.actor', verbose_name='Analog in English'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Analog in English'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country_de',
            field=models.CharField(max_length=30, null=True, verbose_name='Analog in English'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Analog in English'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='Analog in English'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Analog in English'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Analog in English'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='film_director', to='movies_app.actor', verbose_name='Analog in English'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies_app.genre', verbose_name='Analog in English'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movies/', verbose_name='Analog in English'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='', max_length=100, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline_de',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Film title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Film title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Film title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Analog in English'),
        ),
    ]
