# Generated by Django 4.1.1 on 2023-04-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_alter_movie_budget_alter_movie_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_pl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
