# Generated by Django 4.1.1 on 2023-04-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_alter_category_options_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='star',
        ),
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Значення'),
        ),
        migrations.AlterField(
            model_name='reviewviamptt',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reviewviamptt',
            name='text',
            field=models.TextField(max_length=5000),
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
